name: Issue or comment created

on:


jobs:
  posten:
    runs-on: ubuntu-latest
    steps:
    - name: Post issue on Codeberg
      run: |
        URL="https://codeberg.org/"
        REPO="tuxilio/sync-test"
        TOKEN=${{ secrets.GIT_TOKEN }}

        if [ "${{ github.event_name }}" == 'issues' ]; then
          data="{\"title\": \"${{ github.event.issue.title }}\", \"body\": \"${{ github.event.issue.body }}\"}"
          url=$URL"api/v1/repos/"$REPO"/issues"
        else
          data="{\"title\": \"Issue-Kommentar\", \"body\": \"${{ github.event.comment.body }}\"}"
          url=$URL"api/v1/repos/"$REPO"/issues/${{ github.event.issue.number }}/comments"
        fi       
        
        response=$(curl -X POST -H "Authorization: token $TOKEN" -H "Content-Type: application/json" -d "$data" $url)

        echo "API-Answer: $response"
