name: Issue Dankesnachricht

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  issue_danke:
    runs-on: ubuntu-latest
    steps:
    - name: API-Aufruf und Dankesnachricht senden
      if: github.event_name == 'issue_comment' && github.event.action == 'created'
      run: |
        comment_id=$(jq -r .comment.id $GITHUB_EVENT_PATH)
        owner=$(jq -r .repository.owner.login $GITHUB_EVENT_PATH)
        repo=$(jq -r .repository.name $GITHUB_EVENT_PATH)
        issue_number=$(jq -r .issue.number $GITHUB_EVENT_PATH)
        curl -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -d '{"body": "Vielen Dank für Ihren Kommentar zum Issue #'$issue_number'!"}' \
          "https://api.github.com/repos/$owner/$repo/issues/$issue_number/comments/$comment_id"
          echo "RUN"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
