jobs:
  issue_copy:
    name: Copy issue to dest repository
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Transfer issue
        uses: iaia/issue-copier@v1.X
        with:
          GITHUB_OWNER: 'tuxilio'
          GITHUB_REPOSITORY: 'sync-test'
          GITHUB_DEST_REPOSITORY: 'https://codeberg.org/Tuxilio/sync-test'
          GITHUB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
