name: Issue erstellt

on:
  issues:
    types: [opened]

jobs:
  posten:
    runs-on: ubuntu-latest
    steps:
    - name: Poste Issue auf Codeberg
      run: |
        URL="https://codeberg.org/"
        REPO="tuxilio/sync-test"
        TOKEN=${{ secrets.GIT_TOKEN }}

        data="{\"title\": \"${{ github.event.issue.title }}\", \"body\": \"${{ github.event.issue.body }}\"}"
        
        url=$URL"api/v1/repos/"$REPO"/issues"
        response=$(curl -X POST -H "Authorization: token $TOKEN" -H "Content-Type: application/json" -d "$data" $url)

        echo "API-Antwort: $response"

        if [ $(echo "$response" | jq -r ".status_code") == 201 ]; then
          echo "Issue erfolgreich erstellt"
        else
          echo "Fehler beim Erstellen des Issues: $response"
        fi
