name: Issue sync (Codeberg -> GitHub)
on:
  repository_dispatch
jobs:
  issue_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Codeberg -> GitHub Issue sync
        run: |
          echo "Codeberg -> GitHub Issue sync"
          raw_body_raw=${{ github.event.client_payload.body }}
          raw_body=${raw_body_raw#payload=}
          body=$(echo -e "$(echo -n $raw_body | sed 's/+/ /g; s/%/\\x/g')")

          echo "::group::Full body"
          echo "$body" | jq .
          echo "::endgroup::"

          echo "::group::Getting information"
          action=$(echo $body | jq '.action')
          echo Action: $action
          echo "::endgroup::"

          if [ "$action" = '"created"' ]; then
            echo "::group::Creating Issue"

            issue_author=$(echo $body | jq '.comment.user.login')
            issue_avatar_url=$(echo $body | jq '.comment.user.avatar_url')
            issue_number=$(echo $body | jq '.issue.number')
            issue_body=$(echo $body | jq '.comment.body')

            echo Issue Author: $issue_author
            echo Issue User Url: $issue_avatar_url
            echo Issue Number: $issue_number
            echo Issue Body: $issue_body

            issue_body=${issue_body#\"}
            issue_body=${issue_body%\"}

            echo Issue Body edited: $issue_body

            curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GIT_GITHUB_TOKEN }}" \
              https://api.github.com/repos/tuxilio/sync-test/issues/$issue_number/comments \
              d '{"body":"$issue_body"}'

            echo "::endgroup::"
          fi