name: Issue sync (GitHub -> Codeberg)
on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  posten:
    runs-on: ubuntu-latest
    steps:
    - name: Post issue on Codeberg
      run: |
        URL="https://codeberg.org/"
        REPO="tuxilio/sync-test"
        TOKEN=${{ secrets.GIT_TOKEN }}

        if [[ "${{ github.event.issue.body }}" == "| <details><summary></summary>This is an issue created by automatic synchronization.</details> |"* ]]; then
          echo "Already synchronized - nothing to do"

        else        
          if [ "${{ github.event_name }}" == 'issues' ]; then
            data="{\"title\": \"${{ github.event.issue.title }}\", \"body\": \"| <details><summary></summary>This is an issue created by automatic synchronization.</details> | [<img src="https://github.com/${{ github.event.issue.user.login }}.png" width="100">](https://github.com/${{ github.event.issue.user.login }}) | [${{ github.event.issue.user.login }}](https://github.com/${{ github.event.issue.user.login }}) commented on GitHub | [Link to the issue](https://github.com/${{ github.repository }}/issues/${{ github.event.issue.number }})
|-|-|-|-|\n${{ github.event.issue.body }}\"}"
            url=$URL"api/v1/repos/"$REPO"/issues"
          else
            data="{\"title\": \"Issue-Kommentar\", \"body\": \"| <details><summary></summary>This is an issue created by automatic synchronization.</details> | [<img src="https://github.com/${{ github.event.issue.user.login }}.png" width="100">](https://github.com/${{ github.event.issue.user.login }}) | [${{ github.event.issue.user.login }}](https://github.com/${{ github.event.issue.user.login }}) commented on GitHub | [Link to the issue](https://github.com/${{ github.repository }}/issues/${{ github.event.issue.number }})
|-|-|-|-|\n${{ github.event.comment.body }}\"}"
            url=$URL"api/v1/repos/"$REPO"/issues/${{ github.event.issue.number }}/comments"
          fi       
        
          response=$(curl -X POST -H "Authorization: token $TOKEN" -H "Content-Type: application/json" -d "$data" $url)

          echo "API-Answer: $response"
        fi
