name: Codeberg -> GitHub Issue sync
on:
  repository_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print Test
        run: |
          echo "Codeberg -> GitHub Issue sync"
          raw_body=${{ github.event.client_payload.body }}
          body=${raw_body#payload=}
          decoded=$(echo -e "$(echo -n $body | sed 's/+/ /g; s/%/\\x/g')")
          echo "$decoded" | jq .
