# Sync repo to the Forgejo mirror
name: Repo sync (GitHub -> Forgejo)
on:
  push:
    branches:
    - '**'

jobs:
  sync-repo-to-forgejo:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Gather facts"
        run: |
          echo "Repo variables:"
          echo "  FORGEJO_SSH_PUSH_URL: $FORGEJO_SSH_PUSH_URL"
      - name: "Sync repo"
        uses: spyoungtech/mirror-action@v0.5.1
        with:
          REMOTE: "${{ vars.FORGEJO_SSH_PUSH_URL }}"
          GIT_SSH_PRIVATE_KEY: ${{ secrets.FORGEJO_SSH_PRIVATE_KEY }}
          GIT_SSH_NO_VERIFY_HOST: "true"
