name: Issue sync Codeberg -> GitHub
on:
  repository_dispatch
jobs:
  issue_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Codeberg -> GitHub Issue sync
        run: |
          echo "Codeberg -> GitHub Issue sync"
          raw_body_raw=${{ github.event.client_payload.body }}
          raw_body=${raw_body_raw#payload=}
          body=$(echo -e "$(echo -n $raw_body | sed 's/+/ /g; s/%/\\x/g')")

          echo "::group::Full body"
          echo "$body" | jq .
          echo "::endgroup::"

          echo "::group::Getting information"
          action=$(echo $body | jq '.action')
          issue_url=$(echo $body | jq '.issue.url')

          echo Action: $action
          echo API Url: $issue_url
