# Sync repo to the Forgejo mirror
name: Repo sync (GitHub -> Forgejo)
on:
  push:
    branches:
      - '**'
  workflow_dispatch: # Manual dispatch
  schedule:
    - cron: "0 */6 * * *"

jobs:
  sync-repo-to-forgejo:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Gather facts"
        run: |
          echo "Repo variables:"
          echo "  FORGEJO_SSH_PUSH_URL: ${{ vars.FORGEJO_SSH_PUSH_URL }}"
      - name: "Sync repo"
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: "${{ vars.FORGEJO_SSH_PUSH_URL }}"
          ssh_private_key: ${{ secrets.FORGEJO_SSH_PRIVATE_KEY }}
