name: test
on:
  repository_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print Test
        run:
          url_decoded=$(echo -n ${{ github.event.client_payload.body }} | sed 's/+/ /g; s/%/\\x/g' | xargs -0 printf)
          echo "$url_decoded" | jq .