name: test
on:
  repository_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print Test
        run: |
          echo "${{ github.event.client_payload.body }}" | sed 's/+/ /g; s/%/\\x/g' | xargs -0 printf | jq .