name: test
on:
  repository_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print Test
        run: |
          body=${ ${{github.event.client_payload.payload}} #payload=}
          echo ${{ fromJSON($body) }}
