name: test
on:
  repository_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print Test
        run:
          encoded_text=${{ github.event.client_payload.body }}
          url_decoded=$(echo -e "$(echo -n $encoded_text | sed 's/+/ /g; s/%/\\x/g')")
          echo "$url_decoded" | jq .
