name: test
on:
  repository_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print Test
        env:
          api: ${{ toJSON(on.google_form.outputs.answers_map) }}
        run: |
          echo api: $api