name: test
on:
  repository_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print Test
        run: |
          raw_body=${{ github.event.client_payload.payload }}
          body=${raw_body#payload=}
          echo $fromJSON($body)
