name: test
on:
  repository_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print Test
        run: |
          echo "test"
          echo ${{ fromJSON(github.event.client_payload.payload) }}