name: test
on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action'
        type: string
      number:
        description: 'Number'
        type: string
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print Test
        run:
          echo ${{ github.event.client_payload.message }}
