name: test
on:
  repository_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print Test
        env:
          api: ${{ toJSON(${{ github.event.client_payload.body }}) }}
        run: |
          echo api: $api